### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by calebeby** [jstransformers/jstransformer-loader#18]
Does anyone know why this is broken?

https://travis-ci.org/jstransformers/jstransformer-loader

**Comment by RobLoach** [comment]
Likely needs some updates. Might be out of sync with the webpack loader API.

**Comment by ForbesLindesay** [comment]
The build failure seems to imply that webpack is somehow trying to load the `testit` module.  In an ideal world, that would just work, but I'm not sure why webpack is even requiring testit.

**Comment by RobLoach** [comment]
Found this issue pop up from testit's wtfnode usage: http://bit.ly/2smcrwC
```
ERROR in ../~/wtfnode/index.js
Module parse failed: /wtfnode/index.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #!/usr/bin/env node
| 
| 'use strict';
```

Webpack tries to bundle wtfnode, and then explodes because of the  `#`.

**Comment by ForbesLindesay** [comment]
This seems to be fixed now
