### ISSUE TITLE
stop use boilerplate `merge`ing

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/jstransformer-loader#2]
Please, stop use that boilerplate `merge`ing thing - it was awful idea, lookup the commit history - that's absolutely weird, we have generator for yo, we have gulp plugin and etc. 
or can also review http://npm.im/khaos

**Comment by RobLoach** [comment]
The git workflow is documented at https://github.com/jstransformers/boilerplate/wiki#update ... Another thing we could do is [squash the update commits](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) into one. The good news is that once the Boilerplate git history is in, it's much easier to see what is updated from the template.

By using a generator, we miss out on updating the template. Is there a way to get a diff for changes to make it easy to update existing projects to the latest in the template? If you document the generator workflow for updates in a seperate wiki page, we could review it as an alternative.

**Comment by RobLoach** [comment]
Let's discuss over in that issue.
